### ISSUE TITLE
wrong version of InfluxDB?

### ISSUE THREAD

**Issue by napo** [olexs/tesla-apiscraper-to-teslafi-export#10]
Beginning data export
Exporting 1/5: charge state data
Error: flag provided but not defined: -database

**Comment by olexs** [comment]
Yep, this only works with InfluxDB v1, but I used `latest` for the image tag and v2 has been long released. Give me a moment to fix the scripts.

**Comment by olexs** [comment]
Try now. You may have to stop the erroneous container from the first attempt first, it will then delete itself:

```shell
docker stop apiscraper-export-influxdb
```

**Comment by napo** [comment]
nice! It works!
